# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bring < Formula
  desc "CLI for the Bring! shopping list app"
  homepage "https://github.com/julianfbeck/bring-cli"
  version "0.1.2"
  license "MIT"

  on_macos do
    url "https://github.com/julianfbeck/bring-cli/releases/download/v0.1.2/bring-cli-macos-universal.tar.gz"
    sha256 "c1aa7fe8dd679c0873a943c6c4a86141acff13735235ba410177611feda4db26"

    def install
      bin.install "bring"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/julianfbeck/bring-cli/releases/download/v0.1.2/bring-cli-linux-amd64.tar.gz"
      sha256 "ae727a6f2a01098135baeb9112c32a8f92f74ec065d69c765d413c047c8ddb89"
      def install
        bin.install "bring"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/julianfbeck/bring-cli/releases/download/v0.1.2/bring-cli-linux-arm64.tar.gz"
      sha256 "c924fe6431f48dff26e370848b05884bbb0dacc43993426fe8de84e026dbb746"
      def install
        bin.install "bring"
      end
    end
  end

  test do
    system "#{bin}/bring", "--version"
  end
end
