# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bring < Formula
  desc "CLI for the Bring! shopping list app"
  homepage "https://github.com/julianfbeck/bring-cli"
  version "0.1.1"
  license "MIT"

  on_macos do
    url "https://github.com/julianfbeck/bring-cli/releases/download/v0.1.1/bring-cli-macos-universal.tar.gz"
    sha256 "46159d5414de72c508d1587d21729aa5c854daaf9e0b2451e2a4428f0e0e2182"

    def install
      bin.install "bring"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/julianfbeck/bring-cli/releases/download/v0.1.1/bring-cli-linux-amd64.tar.gz"
      sha256 "244319a2a02e61505f034df439ddd1ab70b8277298b4017dca54a2259bfef75d"
      def install
        bin.install "bring"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/julianfbeck/bring-cli/releases/download/v0.1.1/bring-cli-linux-arm64.tar.gz"
      sha256 "e86599943356a5f007ef7352fd488d226dcdea9f39c7221800c18136cf702c24"
      def install
        bin.install "bring"
      end
    end
  end

  test do
    system "#{bin}/bring", "--version"
  end
end
