# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JellyfinDownload < Formula
  desc "CLI to download Jellyfin movies and episodes"
  homepage "https://github.com/julianfbeck/jellyfin-download-cli"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  url "https://github.com/julianfbeck/jellyfin-download-cli/releases/download/v0.1.0/jellyfin-download-macos-universal.tar.gz"
  sha256 "d72d92cbabd7d7a3076e91bd59dd82c2f063dcd41eb3d1d5f656080a4a6f7e30"

  def install
    bin.install "jellyfin-download"
  end

  test do
    system "#{bin}/jellyfin-download", "--version"
  end
end
