# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JellyfinDownload < Formula
  desc "Jellyfin downloader with Plex-ready folder layout"
  homepage "https://github.com/julianfbeck/jellyfin-download-cli"
  version "0.1.1"
  license "MIT"
  depends_on :macos

  url "https://github.com/julianfbeck/jellyfin-download-cli/releases/download/v0.1.1/jellyfin-download-macos-universal.tar.gz"
  sha256 "d61b50c9ee60b0b7164f371c853d3135a348d965a2b1ae75b6308d5a349656df"

  def install
    bin.install "jellyfin-download"
  end

  test do
    system "#{bin}/jellyfin-download", "--version"
  end
end
