# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Overseerr < Formula
  desc "CLI for Overseerr media request management"
  homepage "https://github.com/julianfbeck/overseerr-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    url "https://github.com/julianfbeck/overseerr-cli/releases/download/v0.1.0/overseerr-cli-macos-universal.tar.gz"
    sha256 "5f970986583ba339d92a2ec6f0a708e8e23cc0d5a284ede34a98de5cdef86a66"

    def install
      bin.install "overseerr"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/julianfbeck/overseerr-cli/releases/download/v0.1.0/overseerr-cli-linux-amd64.tar.gz"
      sha256 "5c5a6d2b5d5cbda1e6a523986b29a53064e89ba437b174f0d8eb79380900b048"
      def install
        bin.install "overseerr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/julianfbeck/overseerr-cli/releases/download/v0.1.0/overseerr-cli-linux-arm64.tar.gz"
      sha256 "05d97723490905b2d1b160a317a156952719f34993c7db58763de097cdddcede"
      def install
        bin.install "overseerr"
      end
    end
  end

  test do
    system "#{bin}/overseerr", "--version"
  end
end
