# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Paperless < Formula
  desc "CLI for Paperless-ngx document management"
  homepage "https://github.com/julianfbeck/paperless-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    url "https://github.com/julianfbeck/paperless-cli/releases/download/v0.1.0/paperless-cli-macos-universal.tar.gz"
    sha256 "ab264703f2b7f584acda261a0a06b54e0163e2df2fc5ee522c63b3ab400cb023"

    def install
      bin.install "paperless"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/julianfbeck/paperless-cli/releases/download/v0.1.0/paperless-cli-linux-amd64.tar.gz"
      sha256 "44d809f4f579a4d3ff4476920a6713df5101033bab870b1d7b36ccaff82c25ee"
      def install
        bin.install "paperless"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/julianfbeck/paperless-cli/releases/download/v0.1.0/paperless-cli-linux-arm64.tar.gz"
      sha256 "14a2d9d302a793d02597239dc0ef418de4562635bc3cc0e4c2f34aeae975e6ff"
      def install
        bin.install "paperless"
      end
    end
  end

  test do
    system "#{bin}/paperless", "--version"
  end
end
