# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SearchConsole < Formula
  desc "CLI for Google Search Console reporting"
  homepage "https://github.com/julianfbeck/search-console-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    url "https://github.com/julianfbeck/search-console-cli/releases/download/v0.1.0/search-console-cli-macos-universal.tar.gz"
    sha256 "64ee2a2b62c9a78d450a5a0121dead10893f5b457b3b919f2e2398ae38fb7ec1"

    def install
      bin.install "search-console"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/julianfbeck/search-console-cli/releases/download/v0.1.0/search-console-cli-linux-amd64.tar.gz"
      sha256 "11ce0bd3a84b67ec7283a0aa6c821f9e475151bfdf688e5029906c9d6fec3c0b"
      def install
        bin.install "search-console"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/julianfbeck/search-console-cli/releases/download/v0.1.0/search-console-cli-linux-arm64.tar.gz"
      sha256 "ecb628f47dbe5254e840b091eb187d0fb37db1925e8dc2def9d642036081b852"
      def install
        bin.install "search-console"
      end
    end
  end

  test do
    system "#{bin}/search-console", "--version"
  end
end
