# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SearchConsole < Formula
  desc "CLI for Google Search Console reporting"
  homepage "https://github.com/julianfbeck/search-console-cli"
  version "0.4.0"
  license "MIT"

  on_macos do
    url "https://github.com/julianfbeck/search-console-cli/releases/download/v0.4.0/search-console-cli-macos-universal.tar.gz"
    sha256 "7fb078dafb86db079df957b5b1e6429aa8489cf5603d9d985bb14309fc873419"

    def install
      bin.install "search-console"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/julianfbeck/search-console-cli/releases/download/v0.4.0/search-console-cli-linux-amd64.tar.gz"
      sha256 "33185e7c234a8cb231572bb6fe85efb5c7a5c1060d9713afc8f7c0ca73e8fdc6"
      def install
        bin.install "search-console"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/julianfbeck/search-console-cli/releases/download/v0.4.0/search-console-cli-linux-arm64.tar.gz"
      sha256 "e962f263ce267d3d7a6ec424702a8ab86abc26fbe7c67ec23567bf6c5c81ca8c"
      def install
        bin.install "search-console"
      end
    end
  end

  test do
    system "#{bin}/search-console", "--version"
  end
end
